language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
install:
  - ./mvnw clean
script:
  - ./mvnw install
after_success:
  - ./mvnw cobertura:cobertura coveralls:report
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
